/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsUpstream {
  kind: string
  host?: string
  port?: number
  path?: string
  ipAffinity?: boolean
  ipAffinityTtlMs?: number
  /** Linux process ID of the worker thread (UDS upstreams only). */
  pid?: number
  /** Linux thread ID of the worker thread (UDS upstreams only). */
  tid?: number
  /**
   * Application protocol the upstream speaks: "h2" for cleartext HTTP/2
   * (UDS upstreams only). Omitted = HTTP/1.x.
   */
  protocol?: string
}
export interface JsCertConfig {
  certChain: string | Buffer
  privateKey: string | Buffer
}
export interface JsMtlsConfig {
  clientCaCert: string | Buffer
  requireClientCert?: boolean
}
export interface JsRouteConfig {
  sni: string
  upstreams: Array<JsUpstream>
  terminateTls: boolean
  cert?: JsCertConfig
  mtls?: JsMtlsConfig
  suspended?: boolean
  suspendTimeoutMs?: number
  /**
   * Global rate limit for this route (new connections per second).
   * Connections are silently dropped (RST) when the token bucket is exhausted.
   */
  maxConnectionsPerSecond?: number
  /** Token bucket burst ceiling (defaults to `maxConnectionsPerSecond`). */
  burst?: number
  /**
   * How the real client IP is forwarded to the upstream.
   * "proxyProtocol" (v1, default for UDS), "proxyProtocolV2", "xForwardedFor", or
   * "none" (default for TCP).
   */
  sourceAddressHeader?: string
  /**
   * Which client TLS fingerprint to forward downstream: "ja3", "ja4", or "none"
   * (default). Carried as a PROXY v2 TLV under "proxyProtocolV2", otherwise as an
   * injected X-JA3/X-JA4 HTTP header.
   */
  forwardFingerprint?: string
  /** Advertise h2 in ALPN so clients can negotiate HTTP/2. Default: false. */
  http2?: boolean
}
export interface JsRateLimitConfig {
  connectionsPerSecond: number
  burst?: number
}
export interface JsProtectionConfig {
  rateLimit?: JsRateLimitConfig
  maxConcurrentPerIp?: number
  allowlist?: Array<string>
  blocklist?: Array<string>
  ja3Blocklist?: Array<string>
  /**
   * JA4 fingerprints to block. Each value is the full 36-char JA4 string
   * (t<ver><sni><cc><ec><alpn>_<12hex>_<12hex>); case-insensitive match.
   */
  ja4Blocklist?: Array<string>
  tlsHandshakeTimeoutMs?: number
  requireSni?: boolean
}
export interface JsListenerConfig {
  host?: string
  port: number
  /** Listener protocol: "tls" (default) or "http". */
  mode?: string
  defaultCert?: JsCertConfig
  mtls?: JsMtlsConfig
  maxConnections?: number
  idleTimeoutMs?: number
  protection?: JsProtectionConfig
}
export interface JsProxyConfig {
  listeners: Array<JsListenerConfig>
  routes: Array<JsRouteConfig>
  workerThreads?: number
  readBufferSize?: number
}
export interface JsListenerProtectionHotConfig {
  /** Port of the listener to update. Must match a listener configured at start. */
  port: number
  protection: JsProtectionConfig
}
export interface JsHotConfig {
  routes?: Array<JsRouteConfig>
  /**
   * Per-listener protection updates. Each entry must reference a listener that was
   * started WITH protection; a mismatched port or a port without protection is an error.
   */
  protection?: Array<JsListenerProtectionHotConfig>
}
export interface JsProxyMetrics {
  activeConnections: number
  blockedConnections: number
  pendingSuspended: number
}
export interface JsBlockedIpsInfo {
  rateLimited: Array<string>
  concurrencyLimited: Array<string>
  cidrBlocklist: Array<string>
}
export interface JsResolveRoute {
  upstream: JsUpstream
  terminateTls: boolean
  cert?: JsCertConfig
  mtls?: JsMtlsConfig
  sourceAddressHeader?: string
  forwardFingerprint?: string
  http2?: boolean
}
export declare class SymphonyProxyWrap {
  constructor(config: JsProxyConfig, emitFn: (...args: any[]) => any)
  start(): Promise<void>
  stop(timeoutMs?: number | undefined | null): Promise<void>
  updateConfig(hot: JsHotConfig): void
  metrics(): JsProxyMetrics
  blockedIps(): JsBlockedIpsInfo
  resolveConnection(id: string, route?: JsResolveRoute | undefined | null): void
}
