// Auto-generated napi addon type declarations.
// Do not edit — regenerated by `napi build --dts ts/addon.d.ts`.

export interface JsUpstream {
	kind: string;
	host?: string;
	port?: number;
	path?: string;
	ipAffinity?: boolean;
	ipAffinityTtlMs?: number;
}

export interface JsCertConfig {
	certChain: string | Buffer;
	privateKey: string | Buffer;
}

export interface JsMtlsConfig {
	clientCaCert: string | Buffer;
	requireClientCert?: boolean;
}

export interface JsRouteConfig {
	sni: string;
	upstreams: Array<JsUpstream>;
	terminateTls: boolean;
	cert?: JsCertConfig;
	mtls?: JsMtlsConfig;
	suspended?: boolean;
	suspendTimeoutMs?: number;
}

export interface JsRateLimitConfig {
	connectionsPerSecond: number;
	burst?: number;
}

export interface JsProtectionConfig {
	rateLimit?: JsRateLimitConfig;
	maxConcurrentPerIp?: number;
	allowlist?: Array<string>;
	blocklist?: Array<string>;
	ja3Blocklist?: Array<string>;
	tlsHandshakeTimeoutMs?: number;
	requireSni?: boolean;
}

export interface JsListenerConfig {
	host?: string;
	port: number;
	defaultCert?: JsCertConfig;
	mtls?: JsMtlsConfig;
	maxConnections?: number;
	idleTimeoutMs?: number;
	protection?: JsProtectionConfig;
}

export interface JsProxyConfig {
	listeners: Array<JsListenerConfig>;
	routes: Array<JsRouteConfig>;
	workerThreads?: number;
	readBufferSize?: number;
}

export interface JsHotConfig {
	routes?: Array<JsRouteConfig>;
}

export interface JsProxyMetrics {
	activeConnections: number;
	blockedConnections: number;
	pendingSuspended: number;
}

export interface JsBlockedIpsInfo {
	rateLimited: Array<string>;
	concurrencyLimited: Array<string>;
	cidrBlocklist: Array<string>;
}

export interface JsResolveRoute {
	upstreams: Array<JsUpstream>;
	terminateTls: boolean;
	cert?: JsCertConfig;
	mtls?: JsMtlsConfig;
}

export declare class SymphonyProxyWrap {
	constructor(config: JsProxyConfig, emitFn: (err: Error | null, value: object) => void): void;
	start(): Promise<void>;
	stop(timeoutMs?: number | undefined | null): Promise<void>;
	updateConfig(hot: JsHotConfig): void;
	metrics(): JsProxyMetrics;
	blockedIps(): JsBlockedIpsInfo;
	resolveConnection(id: string, route?: JsResolveRoute | undefined | null): void;
}
