/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsUpstream {
  kind: string
  host?: string
  port?: number
  path?: string
  ipAffinity?: boolean
  ipAffinityTtlMs?: number
  /** Linux process ID of the worker thread (UDS upstreams only). */
  pid?: number
  /** Linux thread ID of the worker thread (UDS upstreams only). */
  tid?: number
  /**
   * Application protocol the upstream speaks: "h2" for cleartext HTTP/2
   * (UDS upstreams only). Omitted = HTTP/1.x.
   */
  protocol?: string
}
export interface JsCertConfig {
  certChain: string | Buffer
  privateKey: string | Buffer
}
export interface JsMtlsConfig {
  clientCaCert: string | Buffer
  requireClientCert?: boolean
}
export interface JsRouteConfig {
  sni: string
  upstreams: Array<JsUpstream>
  terminateTls: boolean
  cert?: JsCertConfig
  mtls?: JsMtlsConfig
  suspended?: boolean
  suspendTimeoutMs?: number
  /**
   * Global rate limit for this route (new connections per second).
   * Connections are silently dropped (RST) when the token bucket is exhausted.
   */
  maxConnectionsPerSecond?: number
  /** Token bucket burst ceiling (defaults to `maxConnectionsPerSecond`). */
  burst?: number
  /**
   * How the real client IP is forwarded to the upstream.
   * "proxyProtocol" (v1, default for UDS), "proxyProtocolV2", "xForwardedFor", or
   * "none" (default for TCP).
   */
  sourceAddressHeader?: string
  /**
   * Which client TLS fingerprint to forward downstream: "ja3", "ja4", or "none"
   * (default). Carried as a PROXY v2 TLV under "proxyProtocolV2", otherwise as an
   * injected X-JA3/X-JA4 HTTP header.
   */
  forwardFingerprint?: string
  /** Advertise h2 in ALPN so clients can negotiate HTTP/2. Default: false. */
  http2?: boolean
  /**
   * The route's application protocol: `'http'` or `'opaque'` (non-HTTP, e.g. MQTT).
   * Required — as a parse-time error, not a silent no-op — whenever the route requests a
   * header-injection forwarding mode (`sourceAddressHeader: 'xForwardedFor'`, or
   * `forwardFingerprint` under any mode other than `'proxyProtocolV2'`): ALPN alone can't
   * tell a native non-HTTP protocol (which negotiates no ALPN) from an HTTPS client that
   * simply offered none, so the declaration must be explicit. Default: `'opaque'`.
   */
  protocol?: string
}
export interface JsRateLimitConfig {
  connectionsPerSecond: number
  burst?: number
}
export interface JsSustainedRateLimitConfig {
  connectionsPerMinute: number
  burst?: number
}
export interface JsPenaltyBoxConfig {
  /** Duration in ms an IP remains blocked after exhausting a rate limit. Default: 600000. */
  durationMs?: number
}
export interface JsProtectionConfig {
  rateLimit?: JsRateLimitConfig
  /** Sustained (per-minute) token bucket — independent of the per-second bucket. */
  sustained?: JsSustainedRateLimitConfig
  /** Penalty box: block an IP for a configurable duration after any rate limit exhaustion. */
  penaltyBox?: JsPenaltyBoxConfig
  maxConcurrentPerIp?: number
  allowlist?: Array<string>
  blocklist?: Array<string>
  ja3Blocklist?: Array<string>
  /**
   * JA4 fingerprints to block. Each value is the full 36-char JA4 string
   * (t<ver><sni><cc><ec><alpn>_<12hex>_<12hex>); case-insensitive match.
   */
  ja4Blocklist?: Array<string>
  tlsHandshakeTimeoutMs?: number
  requireSni?: boolean
}
export interface JsListenerConfig {
  host?: string
  port: number
  /** Listener protocol: "tls" (default) or "http". */
  mode?: string
  defaultCert?: JsCertConfig
  mtls?: JsMtlsConfig
  maxConnections?: number
  idleTimeoutMs?: number
  protection?: JsProtectionConfig
}
export interface JsProxyConfig {
  listeners: Array<JsListenerConfig>
  routes: Array<JsRouteConfig>
  workerThreads?: number
  /**
   * Per-direction copy buffer, in bytes (default 8192). One buffer per direction is held for
   * the whole life of every proxied connection, idle or not, so these are a direct multiplier
   * on per-connection memory: `(client + upstream) × connections`, i.e.
   * `2 × readBufferSize × connections` when both directions use this value.
   */
  readBufferSize?: number
  /** Overrides `readBufferSize` for the client→upstream direction only. */
  clientReadBufferSize?: number
  /** Overrides `readBufferSize` for the upstream→client direction only. */
  upstreamReadBufferSize?: number
}
export interface JsListenerProtectionHotConfig {
  /** Port of the listener to update. Must match a listener configured at start. */
  port: number
  protection: JsProtectionConfig
}
export interface JsHotConfig {
  routes?: Array<JsRouteConfig>
  /**
   * Per-listener protection updates. Each entry must reference a listener that was
   * started WITH protection; a mismatched port or a port without protection is an error.
   */
  protection?: Array<JsListenerProtectionHotConfig>
}
/** A single labelled counter — one entry per block/error reason. */
export interface JsLabeledCount {
  reason: string
  count: number
}
export interface JsListenerMetrics {
  /** "host:port" — matches the `listener` field on emitted events. */
  address: string
  /** "tls" or "http". */
  mode: string
  activeConnections: number
  accepted: number
  blocked: number
  errors: number
  /** Bytes read from clients (client → upstream). */
  bytesReceived: number
  /** Bytes written to clients (upstream → client). */
  bytesSent: number
  blockedByReason: Array<JsLabeledCount>
  errorsByReason: Array<JsLabeledCount>
}
export interface JsProxyMetrics {
  activeConnections: number
  blockedConnections: number
  pendingSuspended: number
  /** Suspended connections that JS resolved with a route. */
  suspendedResolved: number
  /** Suspended connections that timed out or were rejected. */
  suspendedUnresolved: number
  /** Routes currently in the live table, including the default route. */
  routes: number
  /** Routes whose cert failed to build — dropped, or serving a carried-forward last-good cert. */
  failingRoutes: number
  listeners: Array<JsListenerMetrics>
}
export interface JsBlockedIpsInfo {
  rateLimited: Array<string>
  concurrencyLimited: Array<string>
  cidrBlocklist: Array<string>
  /** IPs currently in the penalty box (blocked for a configured duration after rate-limit exhaustion). */
  penaltyBoxed: Array<string>
}
export interface JsResolveRoute {
  upstream: JsUpstream
  terminateTls: boolean
  cert?: JsCertConfig
  mtls?: JsMtlsConfig
  sourceAddressHeader?: string
  forwardFingerprint?: string
  http2?: boolean
  /**
   * See `JsRouteConfig::protocol` — the same declaration, required under the same
   * conditions, for a route resolved via `resolveConnection()`.
   */
  protocol?: string
}
export declare class SymphonyProxyWrap {
  constructor(config: JsProxyConfig, emitFn: (...args: any[]) => any)
  start(): Promise<void>
  stop(timeoutMs?: number | undefined | null): Promise<void>
  updateConfig(hot: JsHotConfig): void
  metrics(): JsProxyMetrics
  blockedIps(): JsBlockedIpsInfo
  resolveConnection(id: string, route?: JsResolveRoute | undefined | null): void
}
